apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: zulip-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: mekumar/zulip:memcached
          imagePullPolicy: IfNotPresent
          args: ["-m", "64", "-c", "1024"] 
          ports:
            - containerPort: 11211
