apiVersion: v1
kind: Service
metadata:
  name: zulip
  labels:
    app: zulip
spec:
  type: NodePort   
  selector:
    app: zulip
  ports:
  - name: smtp
    port: 25
    targetPort: 25
    protocol: TCP
    nodePort: 30225   
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080   # external port
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
    nodePort: 30443   # external port