apiVersion: v1
kind: Secret
metadata:
  name: zulip
  namespace: zulip-app
type: Opaque
stringData:
  POSTGRES_USER: zulip
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
  POSTGRES_DB: zulip
  RABBITMQ_USER: zulip
  RABBITMQ_PASSWORD: cmFiYml0cGFzcw==
  REDIS_PASSWORD: ""
  MEMCACHED_PASSWORD: bWVtY2FjaGUxMjMK
  
