apiVersion: v1
kind: Service
metadata:
  name: zulip
  namespace: zulip-app
  labels:
    app: zulip
spec:
  type: NodePort   # Expose using NodePort
  ports:
    - name: http
      port: 80          # service port inside cluster
      targetPort: 80    # container port
      nodePort: 30080   # fixed external port on every node (range: 30000–32767)
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443   #  external HTTPS port
  selector:
    app: zulip
