apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: zulip-app
  labels:
    app: postgres
spec:
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  clusterIP: None
  