apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: zulip-app
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis