apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: zulip-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: mekumar/zulip:redis
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - |
              echo "requirepass '${REDIS_PASSWORD}'" > /etc/redis.conf
              exec redis-server /etc/redis.conf
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zulip-secrets
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 6379